### ISSUE TITLE
Just a hint about linking to these public dockerfiles

### ISSUE THREAD

**Issue by ovizii** [Patricol/dockerfiles-public#1]
Hi there,

I found you via docker hub: https://hub.docker.com/r/patricol/samba where you are linking to your dockerfiles but that link is broken. The correct link should be https://github.com/Patricol/dockerfiles-public 

btw. I am looking to run a samba server on my NAS and am curious if you have more documentation than what I can currently find on your samba image.

**Comment by Patricol** [comment]
My apologies, the source repo is still not fully public because I haven't wiped some secrets out of its early commit history. (The repo originated from a school project that was quite rushed.)

The samba files are mostly unmodified from what is in the dockerfiles-public repo.

I can try to make the source repository public in the near future to reduce confusion.

Using the samba image will involve creating empty subfolders in a (generally mounted) /config/users folder. A user matching each folder's name will be created, either with a generated password or using a password specified in a `password` file in their subfolder. That password is used for both samba and as the general password for their account.

Not creating any subfolders will result in one default user, named `user` being created.

A mounted `/config/smb.conf` file can be used to change samba settings and specify shares. If unspecified, a default will also be used that shares the `/data` folder to the default `user` user.

**Comment by ovizii** [comment]
thx, I'm going to give it a try.
